name: Android Debug Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug
        working-directory: android

      - name: Rename debug APK
        run: |
          mv android/app/build/outputs/apk/debug/app-debug.apk \
            android/app/build/outputs/apk/debug/forever-jukebox-debug.apk

      - name: Publish debug APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-debug-latest
          name: Android Debug Latest Build
          prerelease: true
          files: android/app/build/outputs/apk/debug/forever-jukebox-debug.apk
